### ISSUE TITLE
center_bin_to_predict in train.yml

### ISSUE THREAD

**Issue by nsamzhao** [FunctionLab/sei-framework#1]
https://github.com/FunctionLab/sei-framework/blob/6bb85803cb52985a86cb6437328813fd4d5ec0fe/train/train.yml#L25-L26
Does it mean to annotate a bin with only 1bp? @kathyxchen

**Comment by kathyxchen** [comment]
Yes that's right, Sei predicts chromatin profiles for the center base pair in a 4096bp sequence
