### ISSUE TITLE
Retrain on subset of chromatin profiles

### ISSUE THREAD

**Issue by smasotti21** [FunctionLab/sei-framework#12]
I wanted to train the Sei Model only on a subset of chromatin profiles than all 21907. I was wondering what needs to be changed to make that happen. I change the seq_chromatin_profiles.txt to the ones which I am interested in (all GM12878). Further, I changed the ./data/seq_chromatin_peaks.bed.gz to have peaks only related to GM12878. I also change the./model/sei.py to have n_genomics=1. However, torch still expects to have 21907 as a size. Can you please guide me with this?

Please let me know, thank you so much!

**Comment by kathyxchen** [comment]
Answered via email, sorry for missing this on github!

**Comment by icdh99** [comment]
Hi @kathyxchen, I would also like to explore retraining of the Sei model on a subset of chromatin tracks. Would you be able to share the information with me as well? Please let me know, thank you in advance!

**Comment by kathyxchen** [comment]
Hi @icdh99 sorry for the late response - can you email me at chen.kathleenm@gmail.com with more details about your use case and what you've tried? the `train` folder in this repository is a good place to start, along with some of the `selene` library tutorials.
