### ISSUE TITLE
NA on precision and roc_auc

### ISSUE THREAD

**Issue by joonan30** [FunctionLab/sei-framework#14]
Hi Kathy,

Thanks for the nice tool. I am trying to train a model with my own ATAC-seq data. It's about 49 datasets so I updated the config file to `n_genomic_features: 49`.  When I checked the train result `selene_sdk.train_model.train.txt `, most of loss results are 0. 

```
loss
0.0009951249016627846
0.0
0.0
0.0
0.0
0.0
0.0
```

Then, the validation result file contains NA for `average_precision` and `roc_auc` are 0. 
 

```
loss    average_precision       roc_auc
0.0     NA      NA
0.0     NA      NA
0.0     NA      NA
```

Do you know what would cause this? 

Thanks,

**Comment by kathyxchen** [comment]
Hi, can you email me at chen.kathleenm@gmail.com with your configuration file information? Happy to help try to reproduce the error and troubleshoot. Thanks!

**Comment by joonan30** [comment]
Thanks Kathy, I just sent it.

**Comment by esignor** [comment]
Good morning,
I'm sorry to disturb you, but I am encountering a similar issue when using the sei-framework ([https://github.com/FunctionLab/sei-framework/issues/30]).
May I know if and how you managed to solve it?
Thank you very much for your help!

Eleonora
