### ISSUE TITLE
Could sei accept sequence (fasta or character) as input?

### ISSUE THREAD

**Issue by WeiCSong** [FunctionLab/sei-framework#2]
Hi sei developer, thanks for the great tool! I notice that the provided pipeline aims to predict delta scores of variants, whereas it is also desirable to directly predict scores for a sequence. I'm not sure which script takes a sequence as input and outputs the score and class of it, and would also like to know whether it is possible to directly input a fasta file to it. Could you help me with this issue? Thank you very much!

**Comment by kathyxchen** [comment]
Apologies for missing this but and appreciate you reaching out via email for your question. For anyone else with a similar idea, we now have a branch `vep_seq` with some preliminary support for sequence inputs.
