### ISSUE TITLE
are the variant predictions done on positive strand sequences?

### ISSUE THREAD

**Issue by okurman** [FunctionLab/sei-framework#7]
Hi!

Sorry if I have missed this information somewhere in the publication, but I couldn't find it. 
I was wondering, are the variant scores done on positive strand sequences of SNPs when generated through the provided scripts? 

Thanks!

**Comment by jzthree** [comment]
Sei prediction is not strand-specific (i.e. it uses both positive and negative strand sequences for prediction). The vcf file has to specify REF and ALT allele based on the '+' strand though.

**Comment by okurman** [comment]
Thank you! Just a follow-up question: if the input is run for both strands anyway, why do the REF/ALT have to be based on the + strand? Would the prediction scores be different depending on the strand of the REF/ALT?

**Comment by jzthree** [comment]
You cannot specify the strand in vcf format so using REF/ALT on + is the convention

**Comment by okurman** [comment]
Got it. Thank you!
