### ISSUE TITLE
Prediction using sequences (vep_cli_seq.py)

### ISSUE THREAD

**Issue by pyareedash** [FunctionLab/sei-framework#9]
Hi developer,
A few queries while using `vep_cli_seq.py` in Sei-Framework,

> What's the difference between `chromatin_profile_ref` (line 28) and `chromatin_profile_ref_adjust` (line 31)? 

> Is there a way to extract column names for `chromatin_profile_file` and `sequence_class_file`?

Thank you :)

**Comment by kathyxchen** [comment]
Hi,
`chromatin_profile_ref` is the chromatin profile predictions made by the Sei deep learning model and `chromatin_profile_ref_adjust` is an adjustment on specific histone mark related profiles to normalize for the effects of nucleosome occupancy. You can read more about why we do this adjustment in the manuscript methods section.

The column names are in the [model](https://github.com/FunctionLab/sei-framework/tree/e2fbc39db3aefe3b1c95206afb9c85381f70e6d3/model) folder `target.names` and `seqclass.names`

**Comment by pyareedash** [comment]
Hi,
Thank you!
